### ISSUE TITLE
Plugin not suspending when CPU is in use by non-Boinc application

### ISSUE THREAD

**Issue by Jojo-A** [hectorespert/boinc-addons#27]
Hi,
as the title says the plugin and thus the CPU usage is not suspending when another non-Boinc process is running.

I used the same work preferences through BAM for different clients. This one with the plugin in HA is the only one that is not suspending work when CPU gets loaded.
I verified that on two ways:
1. started a high-CPU-usage process and checked the logs in the plugin. On my other clients the logs tell you when the CPU gets occupied by another process - not in this case.
2. started the very same high-CPU-usage process once with the plugin running and once with the plugin deactivated. Result: the process gets finished much earlier when the plugin is deactivated.

In this constellation this is really an issue, because each time when HA requires some more resources it becomes quite laggy very slow because the plugin does not suspend :/ .

As said, I use the very same work preferences on multiple clients. The CPU threshold is set very low to 10% and gets fetched correctly by the plugin.
So for me it seems as if the plugin has no access the the CPU usage, so it maybe does not know about the actual CPU load? Maybe a matter of permissions?

**Comment by hectorespert** [comment]
Thanks @Jojo-A for report the issue

> started a high-CPU-usage process and checked the logs in the plugin. On my other clients the logs tell you when the CPU gets occupied by another process - not in this case.

How do you run that process? To try to reproduce it

**Comment by Jojo-A** [comment]
> Thanks @Jojo-A for report the issue
> 
> > started a high-CPU-usage process and checked the logs in the plugin. On my other clients the logs tell you when the CPU gets occupied by another process - not in this case.
> 
> How do you run that process? To try to reproduce it

Hi,
yeah, thats relatively easy. I just compiled an ESPhome project. This is what usually loads the CPU by 100%. Depending an the Project it takes a couple of minutes. But also other background tasks like creating backups or so should definitely load the system by more than 10% (which is my current threshold). I am running on an aarch64 system.
There is nothing else installed on the system but HAOS.

**Comment by hectorespert** [comment]
Hi @Jojo-A 

Could you please verify if the new version fixes that issue in your installation?

**Comment by stiltjack** [comment]
I also have this issue. Previously the plug-in was running at 25% of CPU (as defined in Science United). Now it's running at 100%. I see no way to control this in the configuration.

**Comment by stiltjack** [comment]
Thanks. Uninstalled.
